// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Firebase no está configurado para web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'Firebase solo está configurado para Android en esta aplicación.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFmS8VShDc72_xXZn-XhkVKdKn3tljDJg',
    appId: '1:243956170479:android:3342d7d18e438ccf72651a',
    messagingSenderId: '243956170479',
    projectId: 'cosmeticoshg-reportes',
    storageBucket: 'cosmeticoshg-reportes.firebasestorage.app',
  );
}
